### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by ghost** [fako1024/profiler#1]
Hello,

Would it be possible to please attach a License to this project (the License file is empty) ?

Thank you very much!

**Comment by ghost** [comment]
@fako1024 Would it be possible to add the (In the readme mentioned) LICENSE file ?

**Comment by fako1024** [comment]
@bt-nect I'm not sure if keeping this repo alive is the best idea of times TBH. I haven't maintained it in years, am not even actively using it myself and while the premise is still sound I'm not convinced if there aren't equivalent / better options around by now that don't rely on a clone of the upstream code. IIRC you can achieve similar results by calling `pprof.StartCPUProfile(w)` with an http.ResponseWriter from whatever `ServeMux` you'd like.

**Comment by ghost** [comment]
Ok will replace it then, thanks for the info :)
